### ISSUE TITLE
Build fails on windows

### ISSUE THREAD

**Issue by Ohmnivore** [SempaiGames/openfl-gpg#8]
```
C:\Users\Ohmnivore\Desktop\HAXEDEV\Elasticate>lime build ProjectPrivate.xml andr
oid
openfl-gps-lib: [** JUST IN CASE NOTICE **] Please remember to download and upgr
ade 'Google Play Services Library' on a regular basis. Read more at https://gith
ub.com/fbricker/openfl-gps-lib
Called from ? line 1
Called from CommandLineTools.hx line 995
Called from CommandLineTools.hx line 23
Called from CommandLineTools.hx line 108
Called from CommandLineTools.hx line 205
Called from platforms/AndroidPlatform.hx line 286
Called from /usr/lib/haxe/std/neko/_std/sys/FileSystem.hx line 63
Called from /usr/lib/haxe/std/neko/_std/sys/FileSystem.hx line 54
Uncaught exception - std@sys_file_type

C:\Users\Ohmnivore\Desktop\HAXEDEV\Elasticate>
```

Really not sure what to do here. The AndroidPlatform method:
```
for (dependency in project.dependencies) {
			
			if (dependency.path != "" && FileSystem.isDirectory (dependency.path) && FileSystem.exists (PathHelper.combine (dependency.path, "project.properties"))) {
				
				var name = dependency.name;
				if (name == "") name = "project" + index;
				
				context.ANDROID_LIBRARY_PROJECTS.push ({ name: name, index: index, path: "deps/" + name, source: dependency.path });
				index++;
				
			}
			
		}
```

**Comment by Ohmnivore** [comment]
I'm guessing some dependency path points to an inexistant file/folder so std@sys_file_type in FileSystem (line 54) fails.

**Comment by fbricker** [comment]
Hi, this looks like you don't have the Google Play Games library downloaded from you android device manager?

If you don't have it installed, please read follow the notice instructions.
```
openfl-gps-lib: [** JUST IN CASE NOTICE **] Please remember to download and
upgrade 'Google Play Services Library' on a regular basis.
Read more at https://github.com/fbricker/openfl-gps-lib 
```

**Comment by Ohmnivore** [comment]
I do have it downloaded, so this error is quite mysterious

**Comment by fbricker** [comment]
mmm, this is strange...

If you do have the Google Play Services and the Android Support Library on your android manager, then I just can tell you to check:

1) Do you have multiple Android SDK installed on hour computer? (as you can have multiple android sdk on diffetent paths, some people installs the Play Services libraries on some SDK which is not the same as Lime uses).

2) openfl / lime version (on old versions of Lime, the android SDK environment variables are not set propperly and it can't reach the library inside the android sdk).

3) SDK Folder Name (does your SDK Folder name contains spaces on some part of the path?).

If you can check this, please let me know if some of this solves your issue.

Thanks!

**Comment by fbricker** [comment]
I'm closing the issue due to lack of response. Please write a new comment if you're still having this issue.

**Comment by blaidev** [comment]
me
